
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.9.34728.123
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TodoApi", "TodoApi.csproj", "{E9CBFEDC-41C9-4B9E-AAF7-6EF92E134213}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{E9CBFEDC-41C9-4B9E-AAF7-6EF92E134213}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{E9CBFEDC-41C9-4B9E-AAF7-6EF92E134213}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{E9CBFEDC-41C9-4B9E-AAF7-6EF92E134213}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{E9CBFEDC-41C9-4B9E-AAF7-6EF92E134213}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {5AC4597C-895A-4EC6-A56C-A1851DCB73AF}
	EndGlobalSection
EndGlobal
